carla_service:
  map: "Town04"
  ip: "127.0.0.1"
  port: 2000

driver:
  config: "conf/traffic_manager/default_driver.json"

spawn_points:
  file: "examples/highway_example_car_positions.csv"

rule_interpreter:
  config: "rules/import_rule_examples/yaml/default_rules.yaml"