# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: check-yaml
    - id: check-added-large-files
    - id: check-toml
# apply format fixes
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.4
  hooks:
    # Run the linter.
    - id: ruff
      args: [--select, "C4,W291,W391,E1,E22,E231,E24,E25,E261,E262,E27,E301,E304,E305,E306,E502", --fix, --fix-only, --preview, --ignore, "E116"]
    # Run the formatter.
    #- id: ruff-format
# report from pyproject.toml
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.4
  hooks:
    # Run the linter.
    - id: ruff