speed:
  target_speed: 20.0
  follow_speed_limits: false
  max_speed: 50.0
  speed_decrease: 10.0
  safety_time: 3.0
  min_speed: 5.0
  speed_lim_dist: 3.0
  intersection_speed_decrease: 5.0
  vehicle_percentage_speed_difference: ???
distance:
  min_proximity_threshold: 10.0
  emergency_braking_distance: 5.0
  distance_to_leading_vehicle: ???
lane_change:
  same_lane_time: 0.0
  other_lane_time: 0.0
  lane_change_time: 2.0
  auto_lane_change: true
  random_left_lanechange_percentage: 0.1
  random_right_lanechange_percentage: 0.1
  keep_right_rule_percentage: 0.7
  random_lane_change_interval: 200
obstacles:
  ignore_vehicles: false
  ignore_traffic_lights: false
  ignore_stop_signs: false
  use_bbs_detection: false
  base_tlight_threshold: 5.0
  base_vehicle_threshold: 5.0
  detection_speed_ratio: 1.0
  use_dynamic_speed_threshold: true
  detection_angles:
    walkers_lane_change:
    - 0.0
    - 90.0
    walkers_same_lane:
    - 0.0
    - 60.0
    cars_lane_change:
    - 0.0
    - 180.0
    cars_same_lane:
    - 0.0
    - 30.0
  ignore_lights_percentage: 0.0
  ignore_signs_percentage: 0.0
  ignore_walkers_percentage: 0.0
  dynamic_threshold_by_speed: true
controls:
  max_brake: 0.5
  max_throttle: 0.75
  max_steering: 0.8
  vehicle_lane_offset: 0.0
planner:
  offset: 0.0
emergency:
  throttle: 0.0
  hand_brake: false
  ignore_percentage: 0.0
  hand_brake_modify_chance: 0.0
  do_random_steering: false
  random_steering_range:
  - -0.25
  - 0.25
rss:
  enabled: true

  # For fast vehicles RSS currently is unreliable, disables rss updates when the vehicle is faster than this. TODO: Implement
  rss_max_speed: 30.0
  use_stay_on_road_feature: 'On'
  log_level: info
data_matrix:
  enabled: true
  # When the world uses synchronous mode and sync is true, the data matrix will be updated every sync_interval ticks.
  # A low value will have a negative impact on the fps.
  # If the world uses asynchronous mode or sync is False the data matrix will be updated by a different thread.
  # This increases the fps but updates will be less frequent.
  sync : true
  # The interval in frames after which the data matrix should be updated. Sync must be true.
  sync_interval: 20
