
# Carla Service:
map: "Town04"
host: "127.0.0.1"
port: 2000
sync: true
handle_ticks: true
fps: 20

# Random (GameFramework):
seed: null

# Camera:
width: 1280
height: 720
gamma: 2.2

# Actor

# Use autopilot instead of agent system
autopilot: False

# - External Actor
# Use an external actor from another process, the code will wait until an actor with `rolename` is found
externalActor: True
# The role name that is looked for in the actor list, if externalActor is True
rolename: "hero"

# Vehicle Model
filter: "vehicle.*"
generation: 2

# -------------------------------------------------

# The below settings might need to be implemented manually, see the AgentGameLoop.py file how they are used

loop: True

# If True sets the log level to DEBUG 
debug: True

# After launching to code enter python interactive mode
interactive: False

# -------------------------------------------------

# Agent Settings
# This is the key where the agents settings are stored
# Value is set by other files through the defaults list below.
agent: ???


# -------------------------------------------------
# Hydra Settings
# see https://hydra.cc/docs/configure_hydra/intro/
# -------------------------------------------------

hydra:
  # creates name of the subfolder where a copy of the config is stored.
  # Default .hydra; use null to disable
  output_subdir: .hydra
  run:
    # used to specify the output directory of hydra functions
    # This will create a folder with your command line options e.g.:
    #   outputs/AgentGameLoop/seed=12,experiments=[sync_on,test1]/2024-07-01_12-00-00
    dir: outputs/${hydra.job.name}/${hydra.job.override_dirname}/${now:%Y-%m-%d_%H-%M-%S}
  callbacks:
    # This allows for a rerun of experiments through --experimental-rerun
    # NOTE: Cannot be used with other command-line options or overrides. They will simply be ignored.
    # Note that it is experimental and there are limitations.
    # See: https://hydra.cc/docs/experimental/rerun/
    save_job_info:
      _target_: hydra.experimental.callbacks.PickleJobInfoCallback

# -------------------------------------------------
# Hydra DefaultList
# See https://hydra.cc/docs/advanced/defaults_list/
# For the Grammar syntax see https://hydra.cc/docs/advanced/override_grammar/basic/
# -------------------------------------------------

defaults:
  # _self_ described where this config should be placed; at first position => every config can overwrite this file
  - _self_

  # -------------------------------------------
  #        Agent Default Configuration 
  # -------------------------------------------
  # Describes the default settings of the agent.
  # Format: agent : <filename in ./agent>
  # -------------------------------------------
  - agent : default_settings

  # -------------------------------------------
  # Extensions to the default settings
  # These files are for utility or not often used settings (e.g. the planner)
  # -------------------------------------------

  # Camera settings
  - config_extensions/camera@camera
  
  # Configure the logger to be used
  - config_extensions/job_logging@hydra.job_logging

  # -------------------------------------------
  #    Experiments (fine granular changes)
  # ------------------------------------------- 
  # Overwrite the default settings, with one or more partial configs from the experiments subfolder
  # NOTE: Do not leave a space between the comma and the next entry
  # e.g. 
  #   python my_file.py "experiments=[test_experiment,test_experiment2]"
  # Add a "# @package _global_" in the first line of the experiment; alternatively use experiments@_global_
  # -------------------------------------------
  - experiments : null
  # you can also use one of these two in the command line, to target a specific package
  - experiments@_global_ : null
  - experiments@_agent_ : null

  # NOTE: to use another directory you have two options 
  # 1) add + sign in the command line before the containing folder followed by
  #    python my_file.py +<directory_name>=<file_name in directory>"
  # 2) add your directory to the line below, the + sign then does not become necessary.
  #    <directory_path_in_./conf> : null
  #
  # Optionally you can add @agent or any other @<key> to add it to the specific key
  
  # --------------- HYDRA ----------------------- 

  # Disable Hydra logging
  #- override hydra/hydra_logging: disabled
  # Disables ALL loggers
  # - override hydra/job_logging: disabled  
