verbose: True
debug: True
interactive: False
seed: null

# carla_service:
map: "Town04"
host: "127.0.0.1"
port: 2000
fps: 20
sync: False

loop: True

# camera:
width: 1280
height: 720
gamma: 2.2

# Actor
externalActor: True
rolename: "hero"
filter: "vehicle.*"
generation: 2
autopilot: False

defaults:
  # _self_ described where this config should be placed; at first position => every config can overwrite it
  - _self_
  # Describes the default settings, must have all entries.
  - lunatic_agent_settings@agent
  # Overwrite the default settings, with partial config from the experiements subfolder
  # e.g. python my_file.py "experiments@agent=[test_experiment, test_experiment2]"
  - experiments@agent : null
  # to use another directory you need a + sign
  # python my_file.py +<directory_name>@agent=<file_name in directory>"

# Disable Hydra logging
  - override hydra/hydra_logging: disabled
# Disable writting the output of the run to a .log file
  - override hydra/job_logging: disabled  

hydra:
  # creates no .hydra subfolder that stores the runs config
  # output_subdir: null
  # Will output in the top-level (?)
  run:
    dir: .