verbose: True
debug: True
interactive: False
seed: null

# carla_service:
map: "Town04"
host: "127.0.0.1"
port: 2000
fps: 20
sync: False

loop: True

# camera:
width: 1280
height: 720
gamma: 2.2

# Actor
externalActor: True
rolename: "hero"
filter: "vehicle.*"
generation: 2
autopilot: False

agent:
  class_name: "LunaticAgent"
  config: "conf/lunatic_agent_settings.yaml"

defaults:
  # _self_ described where this config should be placed; at first position => every config can overwrite it
  - _self_
  - agent : conf/lunatic_agent_settings.yaml
# Disable Hydra logging
  - override hydra/hydra_logging: disabled
# Disable writting the output of the run to a .log file
  - override hydra/job_logging: disabled  

hydra:
  # creates no .hydra subfolder that stores the runs config
  # output_subdir: null
  # Will output in the top-level (?)
  run:
    dir: .