verbose: True
debug: True
interactive: False
seed: null

# carla_service:
map: "Town04"
host: "127.0.0.1"
port: 2000
fps: 20
sync: True

loop: True

# camera:
width: 1280
height: 720
gamma: 2.2

# Actor
externalActor: True
rolename: "hero"
filter: "vehicle.*"
generation: 2
autopilot: False

# Agent
# Should be set by another file, see defaults
agent: ???

# -------------------------------------------------
# Hydra DefaultList
# See https://hydra.cc/docs/advanced/defaults_list/
# -------------------------------------------------

defaults:
  # _self_ described where this config should be placed; at first position => every config can overwrite this file
  - _self_

  # -------------------------------------------
  #        Agent Default Configuration 
  # -------------------------------------------
  # Describes the default settings of the agent.
  # Format: <filename>@agent
  # -------------------------------------------
  - agent_default_settings@agent

  # To use a different defaults setting use:
  # TODO: figure out and write here
  # likely needs another file with defaults

  # -------------------------------------------
  # Extensions to the default settings
  # These files are utility or not often used settings
  # -------------------------------------------
  
  # LocalPlanner settings
  - config_extensions/planner@agent.planner
  
  # Interpolation / Aliases
  - config_extensions/interpolation@agent
  
  # Only available during runtime
  - config_extensions/live_info@agent.live_info
  
  # Configure the logger to be used
  - config_extensions/job_logging@hydra.job_logging

  # -------------------------------------------
  #    Experiments (fine granular changes)
  # ------------------------------------------- 
  # Overwrite the default settings, with partial config from the experiments subfolder
  # e.g. 
  #   python my_file.py "experiments@agent=[test_experiment, test_experiment2]"
  #
  # NOTE: to use another directory you have two options 
  # 1) add + sign in the command line before the containing folder followed by @agent
  #    python my_file.py +<directory_name>@agent=<file_name in directory>"
  # 2) add your directory to the line below, the + sign then does not become necessary.
  #    <directory_path_in_./conf>@agent : null
  # -------------------------------------------
  - experiments@agent : null
  
# --------------- HYDRA ----------------------- 

# Disable Hydra logging
  - override hydra/hydra_logging: disabled
# Disables ALL loggers # TODO: but introduces hydras own handler find way to remove.
# - override hydra/job_logging: disabled  

hydra:
  # creates no .hydra subfolder that stores the runs config
  output_subdir: null
  # Will output in the top-level
  run:
    dir: .
