overwrites: {}
live_info:
  current_speed: ???
  current_speed_limit: ???
  velocity_vector: ???
  direction: ???
speed:
  current_speed: ${live_info.current_speed}
  current_speed_limit: ${live_info.current_speed_limit}
  target_speed: 20.0
  follow_speed_limits: false
  max_speed: 50.0
  speed_decrease: 12.0
  safety_time: 3.0
  min_speed: 5.0
  speed_lim_dist: 6.0
  intersection_speed_decrease: 5.0
  vehicle_percentage_speed_difference: ???
  intersection_target_speed: ${min:${.max_speed}, ${subtract:${.current_speed_limit},
    ${.intersection_speed_decrease}}}
distance:
  base_min_distance: 3.0
  distance_ratio: 0.5
  min_proximity_threshold: 12.0
  braking_distance: 6.0
  distance_to_leading_vehicle: ???
lane_change:
  same_lane_time: 0.0
  other_lane_time: 0.0
  lane_change_time: 2.0
  auto_lane_change: true
  random_left_lanechange_percentage: 0.1
  random_right_lanechange_percentage: 0.1
  keep_right_rule_percentage: 0.7
  random_lane_change_interval: 200
obstacles:
  ignore_vehicles: false
  ignore_traffic_lights: false
  ignore_stop_signs: false
  use_bbs_detection: false
  base_tlight_threshold: 5.0
  base_vehicle_threshold: 5.0
  detection_speed_ratio: 1.0
  detection_angles:
    walkers_lane_change:
    - 0.0
    - 90.0
    walkers_same_lane:
    - 0.0
    - 60.0
    cars_lane_change:
    - 0.0
    - 180.0
    cars_same_lane:
    - 0.0
    - 30.0
  ignore_lights_percentage: 0.0
  ignore_signs_percentage: 0.0
  ignore_walkers_percentage: 0.0
  dynamic_threshold_by_speed: true
controls:
  max_brake: 0.5
  max_throttle: 0.75
  max_steering: 0.8
  offset: 0.0
  vehicle_lane_offset: ${planner.offset}
planner:
  dt: ???
  sampling_radius: 2.0
  sampling_resolution: 4.5
  lateral_control_dict:
    K_P: 1.95
    K_I: 0.05
    K_D: 0.2
    dt: ${..dt}
  args_lateral_dict: ${${.lateral_control_dict}}
  longitudinal_control_dict:
    K_P: 1.0
    K_I: 0.05
    K_D: 0.0
    dt: ${..dt}
  args_longitudinal_dict: ${${.longitudinal_control_dict}}
emergency:
  throttle: 0.0
  brake: ${controls.max_brake}
  hand_brake: false
  ignore_percentage: 0.0
  hand_brake_modify_chance: 0.0
  do_random_steering: false
  random_steering_range:
  - -0.25
  - 0.25
rss:
  enabled: true
  use_stay_on_road_feature: 'On'
  log_level: info
