# Currently more explanation of the parameters can be found in the config/default_options/classes

live_info:
  current_speed: null
  current_speed_limit: null
  direction: null

speed:
# NOTE: This is the speed to reach and UPDATED by the planner when using follow speed limits is true.
  target_speed: 20
# Speed not to exceed when using any behavior 
  max_speed: 50

  follow_speed_limits: false

  # AUTOPILOT: Not yet implemented
  # Relative difference below the speed limit
  vehicle_percentage_speed_difference: 30
  # Absolute difference below the speed limit
  speed_lim_dist: 6

  speed_decrease: 12
  safety_time: 3
  min_speed: 5

  # These are information updated by the simulator, they are grouped in the live_info section.
  # For logical reasons these are included here as well.
  # Originally these are referred to as '_speed' & '_speed_limit' and come from the vehicle class.
  current_speed: ${live_info.current_speed}
  current_speed_limit: ${live_info.current_speed_limit}
distance:
  base_min_distance: 3.0
  distance_ratio: 0.5
  min_proximity_threshold: 12
  braking_distance: 6
  # AUTOPILOT: TODO: Check how similar to existing options.
  distance_to_leading_vehicle: 5.0

# AUTOPILOT: Not yet implemented
lane_change:
  auto_lange_change: true
  random_left_lanechange_percentage: 0.1
  random_right_lanechange_percentage: 0.1
  keep_right_rule_percentage: 0.7

obstacles:
  ignore_vehicles: false
  ignore_traffic_lights: false
  ignore_stop_signs: false
  base_tlight_threshold: 5.0
  base_vehicle_threshold: 5.0
  detection_speed_ratio: 1.0
  # AUTOPILOT: Not yet implemented
  ignore_lights_percentage: 0.0
  # AUTOPILOT: Not yet implemented
  ignore_signs_percentage: 0.0
  # AUTOPILOT: Not yet implemented
  ignore_walkers_percentage: 0.0
controls:
  max_brake: 0.5
  max_throttle: 0.75
  max_steering: 0.8
  offset: 0
planner:
  sampling_radius: 2.0
  # NOTE: dt is the simulation speed and should be set from the game loop
  # TODO: Set this to '???' a MISSING value that needs to be updated.
  dt: 0.05
  lateral_control_dict:
    K_P: 1.95
    K_I: 0.05
    K_D: 0.2
    dt: ${..dt}
  longitudinal_control_dict:
    K_P: 1.0
    K_I: 0.05
    K_D: 0
    dt: ${..dt}
  # Aliases that are used in the original code
  args_longitudinal_dict: ${.longitudinal_control_dict}
  args_lateral_dict: ${.lateral_control_dict}
other:
  tailgate_counter: 0
  # Keyword used by autopilot / traffic manager
  vehicle_lane_offset: "${planner.offset}"
  # autopilot: but we likely will not bother:
  update_vehicle_lights: false
unknown:
  # TODO: Should group these in the correct section and update code or here accordingly.
  use_bbs_detection: false
  sampling_resolution: 2.0

# Customizable Lunatic behavior
emergency:
  ignore_percentage: 0.0
  do_random_steering: false
  random_steering_range:
  - -0.25
  - 0.25
  use_hand_brake: false
  use_hand_brake_chance: 0.0

rss:
  enabled: true
  use_stay_on_road_feature: 'On'
  log_level: info

detection_matrix:
  enabled: false
  # When the world uses synchronous mode and sync is true, the data matrix will be updated every sync_interval ticks.
  # A low value will have a negative impact on the fps.
  # If the world uses asynchronous mode or sync is False the data matrix will be updated by a different thread.
  # This increases the fps but updates will be less frequent.
  sync : true
  # The interval in frames after which the data matrix should be updated. Sync must be true.
  sync_interval: 20